name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build jars
        id: build_jars
        run: ./gradlew assemble

      - name: Build docker image
        id: build_docker
        run: ./gradlew bootBuildImage

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Tag docker image as latest
        run: docker tag ${{ steps.build_docker.outputs.image }} ${{ steps.build_docker.outputs.image_base }}:latest

      - name: Push docker image
        run: |
          docker push ${{ steps.build_docker.outputs.image }}
          docker push ${{ steps.build_docker.outputs.image_base }}:latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.build_jars.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: plugin/build/libs/tenantsecrets-plugin-${{ steps.build_jars.outputs.version }}.jar
          asset_name: tenantsecrets-plugin-${{ steps.build_jars.outputs.version }}.jar
          asset_content_type: application/java-archive
